version: '3'
services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://backend:8080
    ports:
      - "3000:3000"

  # backend:
  #   build: 
  #     context: ./server
  #     dockerfile: Dockerfile
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tododb
  #     - SPRING_DATASOURCE_USERNAME=kennedy
  #     - SPRING_DATASOURCE_PASSWORD=password
  #   ports:
  #     - "8080:8080"
  

